#pragma once

typedef struct _S_PT_CHANNEL_NICKNAME
{
	WCHAR USER_ID[32];
	WCHAR NICK_NAME[32];
} S_PT_CHANNEL_NICKNAME;

typedef struct _S_PT_CHANNEL_NICKNAME_SUCC_U
{
	WCHAR USER_ID[32];
	WCHAR NICK_NAME[32];
} S_PT_CHANNEL_NICKNAME_SUCC_U;

typedef struct _S_PT_CHANNEL_NICKNAME_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_CHANNEL_NICKNAME_FAIL_U;

typedef struct _S_PT_CHANNEL_REQ_USERINFO
{
	WCHAR USER_ID[32];
} S_PT_CHANNEL_REQ_USERINFO;

typedef struct _S_PT_CHANNEL_REQ_USERINFO_SUCC_U
{
	WCHAR NICK_NAME[32];
	INT64 GAME_MONEY;
	INT64 EXP;
	INT64 CHAR_INDEX_1;
	INT64 CHAR_INDEX_2;
	INT64 CHAR_INDEX_3;
} S_PT_CHANNEL_REQ_USERINFO_SUCC_U;

typedef struct _S_PT_CHANNEL_REQ_USERINFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_CHANNEL_REQ_USERINFO_FAIL_U;

typedef struct _S_PT_CHANNEL_REQ_CHARINFO
{
	USHORT CHAR_SLOT;
} S_PT_CHANNEL_REQ_CHARINFO;

typedef struct _S_PT_CHANNEL_REQ_CHARINFO_SUCC_U
{
	INT64 CHAR_INDEX;
	WCHAR NAME[32];
	INT JOB;
	INT TYPE;
	INT64 EXP;
	INT HEAD_TYPE;
	INT CHEST_TYPE;
	INT PANTS_TYPE;
	INT GLOVES_TYPE;
	INT SOCKS_TYPE;
	INT SHOES_TYPE;
	INT ACCESSORY_TYPE;
	INT SKILL_TYPE_1;
	INT SKILL_TYPE_2;
	INT SKILL_TYPE_3;
	INT SPECIAL_SHOOT_TYPE_1;
	INT SPECIAL_SHOOT_TYPE_2;
	INT SPECIAL_SHOOT_TYPE_3;
} S_PT_CHANNEL_REQ_CHARINFO_SUCC_U;

typedef struct _S_PT_CHANNEL_REQ_CHARINFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_CHANNEL_REQ_CHARINFO_FAIL_U;

typedef struct _S_PT_CHANNEL_CHECK_CHARACTER_NAME
{
	WCHAR NAME[32];
} S_PT_CHANNEL_CHECK_CHARACTER_NAME;

typedef struct _S_PT_CHANNEL_CHECK_CHARACTER_NAME_SUCC_U
{
} S_PT_CHANNEL_CHECK_CHARACTER_NAME_SUCC_U;

typedef struct _S_PT_CHANNEL_CHECK_CHARACTER_NAME_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_CHANNEL_CHECK_CHARACTER_NAME_FAIL_U;

typedef struct _S_PT_CHANNEL_CREATE_CHARACTER
{
	WCHAR NAME[32];
	INT JOB;
	INT TYPE;
	USHORT SLOT;
} S_PT_CHANNEL_CREATE_CHARACTER;

typedef struct _S_PT_CHANNEL_CREATE_CHARACTER_SUCC_U
{
} S_PT_CHANNEL_CREATE_CHARACTER_SUCC_U;

typedef struct _S_PT_CHANNEL_CREATE_CHARACTER_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_CHANNEL_CREATE_CHARACTER_FAIL_U;

typedef struct _S_PT_CHANNEL_EQUIP
{
	INT64 CHAR_INDEX;
	USHORT EQUIP_LOCATION;
	INT ITEM_TYPE;
} S_PT_CHANNEL_EQUIP;

typedef struct _S_PT_CHANNEL_EQUIP_SUCC_U
{
} S_PT_CHANNEL_EQUIP_SUCC_U;

typedef struct _S_PT_CHANNEL_EQUIP_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_CHANNEL_EQUIP_FAIL_U;

typedef struct _S_PT_CHANNEL_CHARACTER_SELECT
{
	USHORT SLOT;
} S_PT_CHANNEL_CHARACTER_SELECT;

typedef struct _S_PT_CHANNEL_CHARACTER_SELECT_SUCC_U
{
} S_PT_CHANNEL_CHARACTER_SELECT_SUCC_U;

typedef struct _S_PT_CHANNEL_CHARACTER_SELECT_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_CHANNEL_CHARACTER_SELECT_FAIL_U;

typedef struct _S_PT_CHANNEL_ENTER
{
	WCHAR USER_ID[32];
	WCHAR VIRTUAL_ADDRESS[32];
	USHORT VIRTUAL_PORT;
} S_PT_CHANNEL_ENTER;

typedef struct _S_PT_CHANNEL_ENTER_SUCC_U
{
	DWORD_PTR SESSION_ID;
	WCHAR VIRTUAL_ADDRESS[32];
	USHORT VIRTUAL_PORT;
	WCHAR REAL_ADDRESS[32];
	USHORT REAL_PORT;
} S_PT_CHANNEL_ENTER_SUCC_U;

typedef struct _S_PT_CHANNEL_ENTER_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_CHANNEL_ENTER_FAIL_U;

typedef struct _S_PT_ROOM_QUICK_JOIN
{
} S_PT_ROOM_QUICK_JOIN;

typedef struct _S_PT_ROOM_QUICK_JOIN_SUCC_U
{
} S_PT_ROOM_QUICK_JOIN_SUCC_U;

typedef struct _S_PT_ROOM_QUICK_JOIN_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_QUICK_JOIN_FAIL_U;

typedef struct _S_PT_ROOM_ENTER_M
{
	DWORD SLOT_POSITION;
	WCHAR USER_ID[32];
	DWORD_PTR SESSION_ID;
	WCHAR VIRTUAL_ADDRESS[32];
	USHORT VIRTUAL_PORT;
	WCHAR REAL_ADDRESS[32];
	USHORT REAL_PORT;
} S_PT_ROOM_ENTER_M;

typedef struct _S_PT_ROOM_REQ_INFO
{
} S_PT_ROOM_REQ_INFO;

typedef struct _S_PT_ROOM_REQ_INFO_SUCC_U
{
	DWORD ROOM_INDEX;
	WCHAR TITLE[32];
	DWORD MAP_INDEX;
	USHORT CURRENT_USER_COUNT;
	DWORD_PTR ROOT_USER_SESSION_ID;
	SLOT_USER_DATA DATA[8];
} S_PT_ROOM_REQ_INFO_SUCC_U;

typedef struct _S_PT_ROOM_REQ_INFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_REQ_INFO_FAIL_U;

typedef struct _S_PT_ROOM_LEAVE
{
} S_PT_ROOM_LEAVE;

typedef struct _S_PT_ROOM_LEAVE_SUCC_U
{
} S_PT_ROOM_LEAVE_SUCC_U;

typedef struct _S_PT_ROOM_LEAVE_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_LEAVE_FAIL_U;

typedef struct _S_PT_ROOM_LEAVE_M
{
	DWORD_PTR SESSION_ID;
	DWORD_PTR ROOT_USER_SESSION_ID;
} S_PT_ROOM_LEAVE_M;

typedef struct _S_PT_ROOM_MAP_CHANGE
{
	DWORD MAP_INDEX;
} S_PT_ROOM_MAP_CHANGE;

typedef struct _S_PT_ROOM_MAP_CHANGE_SUCC_U
{
} S_PT_ROOM_MAP_CHANGE_SUCC_U;

typedef struct _S_PT_ROOM_MAP_CHANGE_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_MAP_CHANGE_FAIL_U;

typedef struct _S_PT_ROOM_MAP_CHANGE_M
{
	DWORD MAP_INDEX;
} S_PT_ROOM_MAP_CHANGE_M;

typedef struct _S_PT_ROOM_CHATTING
{
	WCHAR CHAT[256];
} S_PT_ROOM_CHATTING;

typedef struct _S_PT_ROOM_CHATTING_SUCC_U
{
} S_PT_ROOM_CHATTING_SUCC_U;

typedef struct _S_PT_ROOM_CHATTING_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_CHATTING_FAIL_U;

typedef struct _S_PT_ROOM_CHATTING_M
{
	DWORD_PTR SESSION_ID;
	WCHAR CHAT[256];
} S_PT_ROOM_CHATTING_M;

typedef struct _S_PT_ROOM_READY
{
	BOOL READY;
} S_PT_ROOM_READY;

typedef struct _S_PT_ROOM_READY_SUCC_U
{
} S_PT_ROOM_READY_SUCC_U;

typedef struct _S_PT_ROOM_READY_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_READY_FAIL_U;

typedef struct _S_PT_ROOM_READY_M
{
	DWORD_PTR SESSION_ID;
	BOOL READY;
} S_PT_ROOM_READY_M;

typedef struct _S_PT_ROOM_START
{
} S_PT_ROOM_START;

typedef struct _S_PT_ROOM_START_SUCC_U
{
} S_PT_ROOM_START_SUCC_U;

typedef struct _S_PT_ROOM_START_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_ROOM_START_FAIL_U;

typedef struct _S_PT_ROOM_START_M
{
} S_PT_ROOM_START_M;

typedef struct _S_PT_GAME_LOAD_COMPLETE
{
} S_PT_GAME_LOAD_COMPLETE;

typedef struct _S_PT_GAME_LOAD_COMPLETE_SUCC_U
{
} S_PT_GAME_LOAD_COMPLETE_SUCC_U;

typedef struct _S_PT_GAME_LOAD_COMPLETE_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_LOAD_COMPLETE_FAIL_U;

typedef struct _S_PT_GAME_LOAD_COMPLETE_M
{
	DWORD_PTR SESSION_ID;
} S_PT_GAME_LOAD_COMPLETE_M;

typedef struct _S_PT_GAME_ALL_LOAD_COMPLETE_M
{
} S_PT_GAME_ALL_LOAD_COMPLETE_M;

typedef struct _S_PT_GAME_INTRO_COMPLETE
{
} S_PT_GAME_INTRO_COMPLETE;

typedef struct _S_PT_GAME_INTRO_COMPLETE_SUCC_U
{
} S_PT_GAME_INTRO_COMPLETE_SUCC_U;

typedef struct _S_PT_GAME_INTRO_COMPLETE_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_INTRO_COMPLETE_FAIL_U;

typedef struct _S_PT_GAME_INTRO_COMPLETE_M
{
	DWORD_PTR SESSION_ID;
} S_PT_GAME_INTRO_COMPLETE_M;

typedef struct _S_PT_GAME_ALL_INTRO_COMPLETE_M
{
} S_PT_GAME_ALL_INTRO_COMPLETE_M;

typedef struct _S_PT_GAME_START_M
{
} S_PT_GAME_START_M;

typedef struct _S_PT_GAME_END_M
{
} S_PT_GAME_END_M;

typedef struct _S_PT_GAME_PASS_INFO
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
} S_PT_GAME_PASS_INFO;

typedef struct _S_PT_GAME_PASS_INFO_SUCC_U
{
} S_PT_GAME_PASS_INFO_SUCC_U;

typedef struct _S_PT_GAME_PASS_INFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_PASS_INFO_FAIL_U;

typedef struct _S_PT_GAME_PASS_INFO_M
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
} S_PT_GAME_PASS_INFO_M;

typedef struct _S_PT_GAME_SHOOT_INFO
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
	USHORT SHOOT_POWER;
} S_PT_GAME_SHOOT_INFO;

typedef struct _S_PT_GAME_SHOOT_INFO_SUCC_U
{
} S_PT_GAME_SHOOT_INFO_SUCC_U;

typedef struct _S_PT_GAME_SHOOT_INFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_SHOOT_INFO_FAIL_U;

typedef struct _S_PT_GAME_SHOOT_INFO_M
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
	USHORT SHOOT_POWER;
} S_PT_GAME_SHOOT_INFO_M;

typedef struct _S_PT_GAME_HIT_INFO
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
	USHORT SHOOT_POWER;
} S_PT_GAME_HIT_INFO;

typedef struct _S_PT_GAME_HIT_INFO_SUCC_U
{
} S_PT_GAME_HIT_INFO_SUCC_U;

typedef struct _S_PT_GAME_HIT_INFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_HIT_INFO_FAIL_U;

typedef struct _S_PT_GAME_HIT_INFO_M
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
	USHORT SHOOT_POWER;
} S_PT_GAME_HIT_INFO_M;

typedef struct _S_PT_GAME_SHOOT_RECEIVE_INFO
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
	USHORT SHOOT_POWER;
} S_PT_GAME_SHOOT_RECEIVE_INFO;

typedef struct _S_PT_GAME_SHOOT_RECEIVE_INFO_SUCC_U
{
} S_PT_GAME_SHOOT_RECEIVE_INFO_SUCC_U;

typedef struct _S_PT_GAME_SHOOT_RECEIVE_INFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_SHOOT_RECEIVE_INFO_FAIL_U;

typedef struct _S_PT_GAME_SHOOT_RECEIVE_INFO_M
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
	USHORT SHOOT_POWER;
} S_PT_GAME_SHOOT_RECEIVE_INFO_M;

typedef struct _S_PT_GAME_PASS_RECEIVE_INFO
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
} S_PT_GAME_PASS_RECEIVE_INFO;

typedef struct _S_PT_GAME_PASS_RECEIVE_INFO_SUCC_U
{
} S_PT_GAME_PASS_RECEIVE_INFO_SUCC_U;

typedef struct _S_PT_GAME_PASS_RECEIVE_INFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_PASS_RECEIVE_INFO_FAIL_U;

typedef struct _S_PT_GAME_PASS_RECEIVE_INFO_M
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
} S_PT_GAME_PASS_RECEIVE_INFO_M;

typedef struct _S_PT_GAME_FIELDBALL
{
	DWORD_PTR DROP_SESSION_ID;
} S_PT_GAME_FIELDBALL;

typedef struct _S_PT_GAME_FIELDBALL_SUCC_U
{
} S_PT_GAME_FIELDBALL_SUCC_U;

typedef struct _S_PT_GAME_FIELDBALL_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_FIELDBALL_FAIL_U;

typedef struct _S_PT_GAME_FIELDBALL_M
{
	DWORD_PTR DROP_SESSION_ID;
} S_PT_GAME_FIELDBALL_M;

typedef struct _S_PT_GAME_GET_FIELDBALL
{
	DWORD_PTR GET_SESSION_ID;
	DWORD PARAMETER;
} S_PT_GAME_GET_FIELDBALL;

typedef struct _S_PT_GAME_GET_FIELDBALL_SUCC_U
{
} S_PT_GAME_GET_FIELDBALL_SUCC_U;

typedef struct _S_PT_GAME_GET_FIELDBALL_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_GET_FIELDBALL_FAIL_U;

typedef struct _S_PT_GAME_GET_FIELDBALL_M
{
	DWORD_PTR GET_SESSION_ID;
	DWORD PARAMETER;
} S_PT_GAME_GET_FIELDBALL_M;

typedef struct _S_PT_GAME_PC_INFO_CHANGED_M
{
	DWORD_PTR SESSION_ID;
	DWORD HP;
	DWORD AP;
} S_PT_GAME_PC_INFO_CHANGED_M;

typedef struct _S_PT_GAME_OUT_INFO_M
{
	DWORD_PTR SESSION_ID;
} S_PT_GAME_OUT_INFO_M;

typedef struct _S_PT_GAME_RESULT_M
{
	BOOL WIN_TEAM;
	DWORD TEAM0_TOTAL_HP;
	DWORD TEAM1_TOTAL_HP;
	DWORD GET_GAME_MONEY;
} S_PT_GAME_RESULT_M;

typedef struct _S_PT_GAME_CHANGE_BALLOWNER
{
	DWORD_PTR NEW_OWNER_SESSION_ID;
} S_PT_GAME_CHANGE_BALLOWNER;

typedef struct _S_PT_GAME_CHANGE_BALLOWNER_M
{
	DWORD_PTR NEW_OWNER_SESSION_ID;
} S_PT_GAME_CHANGE_BALLOWNER_M;

typedef struct _S_PT_GAME_SPECIAL_SHOOT_INFO
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
	USHORT SHOOT_TYPE;
} S_PT_GAME_SPECIAL_SHOOT_INFO;

typedef struct _S_PT_GAME_SPECIAL_SHOOT_INFO_SUCC_U
{
} S_PT_GAME_SPECIAL_SHOOT_INFO_SUCC_U;

typedef struct _S_PT_GAME_SPECIAL_SHOOT_INFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_SPECIAL_SHOOT_INFO_FAIL_U;

typedef struct _S_PT_GAME_SPECIAL_SHOOT_INFO_M
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
	USHORT SHOOT_TYPE;
} S_PT_GAME_SPECIAL_SHOOT_INFO_M;

typedef struct _S_PT_GAME_SPECIAL_HIT_INFO
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
	USHORT SHOOT_TYPE;
} S_PT_GAME_SPECIAL_HIT_INFO;

typedef struct _S_PT_GAME_SPECIAL_HIT_INFO_SUCC_U
{
} S_PT_GAME_SPECIAL_HIT_INFO_SUCC_U;

typedef struct _S_PT_GAME_SPECIAL_HIT_INFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_SPECIAL_HIT_INFO_FAIL_U;

typedef struct _S_PT_GAME_SPECIAL_HIT_INFO_M
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
	USHORT SHOOT_TYPE;
} S_PT_GAME_SPECIAL_HIT_INFO_M;

typedef struct _S_PT_GAME_SPECIAL_RECEIVE_INFO
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
	USHORT SHOOT_TYPE;
} S_PT_GAME_SPECIAL_RECEIVE_INFO;

typedef struct _S_PT_GAME_SPECIAL_RECEIVE_INFO_SUCC_U
{
} S_PT_GAME_SPECIAL_RECEIVE_INFO_SUCC_U;

typedef struct _S_PT_GAME_SPECIAL_RECEIVE_INFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_SPECIAL_RECEIVE_INFO_FAIL_U;

typedef struct _S_PT_GAME_SPECIAL_RECEIVE_INFO_M
{
	DWORD_PTR SHOOTER_SESSION_ID;
	DWORD_PTR TARGET_SESSION_ID;
	USHORT SHOOT_TYPE;
} S_PT_GAME_SPECIAL_RECEIVE_INFO_M;

typedef struct _S_PT_GAME_SKILL_INFO
{
	DWORD_PTR SKILL_SESSION_ID;
	USHORT SKILL_TYPE;
	DWORD_PTR TARGET_SESSION_ID;
} S_PT_GAME_SKILL_INFO;

typedef struct _S_PT_GAME_SKILL_INFO_SUCC_U
{
} S_PT_GAME_SKILL_INFO_SUCC_U;

typedef struct _S_PT_GAME_SKILL_INFO_FAIL_U
{
	DWORD ERROR_CODE;
} S_PT_GAME_SKILL_INFO_FAIL_U;

typedef struct _S_PT_GAME_SKILL_INFO_M
{
	DWORD_PTR SKILL_SESSION_ID;
	USHORT SKILL_TYPE;
	DWORD_PTR TARGET_SESSION_ID;
} S_PT_GAME_SKILL_INFO_M;

typedef struct _S_PT_GAME_EXPLOSION_READY_M
{
	DWORD_PTR EXPLOSION_SESSION_ID;
} S_PT_GAME_EXPLOSION_READY_M;

typedef struct _S_PT_GAME_EXPLOSION_M
{
	DWORD_PTR EXPLOSION_SESSION_ID;
} S_PT_GAME_EXPLOSION_M;

typedef struct _S_PT_GAME_TURNOVER_READY_M
{
} S_PT_GAME_TURNOVER_READY_M;

typedef struct _S_PT_GAME_TURNOVER_M
{
} S_PT_GAME_TURNOVER_M;

