#ifndef  __Protocol_H
#define  __Protocol_H

enum USProtocolList
{
	USProtocolBase = 10000,

									UC_CONNECTIONSUCCESS_ACK,
	UC_LOADERVERSION_REQ,			UC_LOADERVERSION_ACK,
	UC_CLIENTVERSION_REQ,			UC_CLIENTVERSION_ACK,
	UC_UPDATELOADERLIST_REQ,		UC_UPDATELOADERLIST_ACK,
	UC_UPDATECLIENTLIST_REQ,		UC_UPDATECLIENTLIST_ACK
};

#endif