#ifndef  __Protocol_H
#define  __Protocol_H

//  Game server global protocol
enum GSProtocolList
{
							GS_CONNECTIONSUCCESS_ACK = 0
};

//  Game server - Game client
enum GGProtocolList
{
							GG_BASE = 100,
	GG_ENTERGAMEROOM_REQ,	GG_ENTERGAMEROOM_ACK,
	GG_USERLIST_REQ,		GG_USERLIST_ACK,
	GG_CHATMESSAGE_REQ,		GG_CHATMESSAGE_ACK,
	GG_LEAVEGAMEROOM_REQ,	GG_LEAVEGAMEROOM_ACK,

	GG_READY_REQ,			GG_READY_ACK,
	GG_STARTGAME_REQ,		GG_STARTGAME_ACK,
	GG_NEWBLOCK_REQ,		GG_NEWBLOCK_ACK,
	GG_MOVEBLOCK_REQ,		GG_MOVEBLOCK_ACK,
	GG_FIXBLOCK_REQ,		GG_FIXBLOCK_ACK,
	GG_GAMEOVER_REQ,		GG_GAMEOVER_ACK
};

#endif